### ISSUE TITLE
g++: error: missing argument to ‘-l’

### ISSUE THREAD

**Issue by schumannd** [lucyking/pickinect#1]
When trying to make i first got an error saying openCV was not found.

I then used this [fix](https://prateekvjoshi.com/2013/10/18/package-opencv-not-found-lets-find-it/) for that.

Now I get:
echo `rm *.png`
rm: cannot remove ‘*.png’: No such file or directory

g++ `pkg-config --cflags opencv` -o main main.cpp `pkg-config --libs opencv`
g++: error: missing argument to ‘-l’
Makefile:2: recipe for target 'main' failed
make: **\* [main] Error 1

**Comment by schumannd** [comment]
I think I don't have openCV installed after all.

**Comment by lucyking** [comment]
Yes, you should install opencv lib manually first.
If you meet problem in shell apt-get install *. You can use Synaptic to install all depends.

echo `rm *.png` is just try to remove old *.png, just ingore this warning.

**Comment by schumannd** [comment]
searching synaptic didn't help. I did `sudo apt-get install libopencv-dev python-opencv` but this did not remove `g++: error: missing argument to ‘-l’`

I am now manually building openCV and hoping I don't run out of space.

**Comment by lucyking** [comment]
Wish the building will be successful. In another way you can:
1. apt-get update
2. apt-get install synaptic
3. run `synaptic` in bash. Then type _opencv_ in its search bar , click and install opencv.It will solve all depends automatically.
